project:
  type: website
  output-dir: docs

website:
  title: "michellelam777.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
format:
  html:
    theme:
      light: yeti
      dark: slate
    css: styles.css
    
editor: visual

