project:
  type: website
  output-dir: docs

website:
  title: "Michelle Lam"
  favicon: images/logo-2.png
  page-footer:
    background: light
    left: 
      - "Copyright 2023, Michelle Lam"
  navbar:
    title: false
    logo: images/logo-2.png
    logo-alt: "Michelle Lam"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume/lam_michelle_resume.pdf
        text: Resume
      - posts.qmd
    
format:
  html:
    theme: 
      - mystyles.scss
    mainfont: Open Sans
editor: visual

