---
title: "About"
---

Michelle Lam is currently pursuing a Master of Environmental Data Science (MEDS) at the University of California, Santa Barbara Bren School of Environmental Science & Management. Michelle graduated from Santa Clara University in 2017 with a B.S. in Environmental Science with an emphasis on water, energy, and technology. During her time at Santa Clara, she worked for a municipal utility promoting energy efficiency programs, which sparked her interest in renewable energy and sustainability in the built environment. After graduating, she further delved into the renewable energy sector working as a Business Systems Analyst for a residential solar company. In that role, she gained first-hand experience managing and using data in various business applications to drive decisions while expanding her knowledge of the solar industry. With her master's degree, she hopes to use data science to further the development of renewable energy and help businesses and organizations create a sustainable built environment.

<h1>this is my h1 element</h1>

<h1 class="title">this is a red h1 element</h1>

<p>this is my paragraph</p>

<p class="title">this is my red paragraph</p>

<h3 class="custom-subtitle">hello</h3>

<h3>hi</h3>
